name: Deploy node.js application

on:
  push: 
    branches: 
      - master

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t divyanshubisht169/nodejs-app .
      - name: Publish image to docker hub
        run: docker push divyanshubisht169/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Pull image from docker hub
        run: docker pull divyanshubisht169/nodejs-app:latest
      - name: Run docker container
        run: docker run -d -p 8000:8000 --name nodejs-app-container -e NODE_MONOGDB_PASSWROD='${{ secrets.NODE_MONOGDB_PASSWROD }}' divyanshubisht169/nodejs-app